In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("qoute_dataset.csv")

In [4]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [5]:
df['quote'][0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

In [6]:
df.shape

(3038, 2)

In [7]:
quotes = df['quote']

In [8]:
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [9]:
import string
translator = str.maketrans('', '', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))
quotes = df['quote'].apply(lambda x: x.translate(translator)).str.lower()

In [10]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [11]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [12]:
vocab_size = 8978
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quotes)

In [13]:
word_index = tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [14]:
sequence = tokenizer.texts_to_sequences(quotes)

In [15]:
quotes[0]

'“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”'

In [16]:
sequence[0]

[713,
 62,
 29,
 19,
 16,
 946,
 10,
 7,
 5,
 1156,
 8,
 70,
 293,
 10,
 145,
 12,
 809,
 104,
 752,
 70,
 2461]

In [17]:
X=[]
y=[]

for seq in sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [18]:
len(X)

85270

In [19]:
len(y)

85270

In [20]:
max_len = max(len(x) for x in X)
print(max_len)

745

In [21]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [22]:
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

In [23]:
y = np.array(y)

In [24]:
X_padded.shape

(85270, 745)

In [25]:
from tensorflow.keras.utils import to_categorical

In [26]:
y_one_hot = to_categorical(y,num_classes=vocab_size)

In [27]:
y.shape

(85270,)

In [28]:
y_one_hot.shape

(85270, 8978)

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,SimpleRNN

In [30]:
embedding_dim = 50
rnn_units = 128

In [31]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [32]:

rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [33]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [35]:

lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [36]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [37]:
epochs = 100
batch_size = 128

rnn_history = rnn_model.fit(
   X_padded, y_one_hot,
  epochs=epochs,
  batch_size=batch_size,
  validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 47s 71ms/step - accuracy: 0.0459 - loss: 6.6828 - val_accuracy: 0.0593 - val_loss: 6.4898
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 66ms/step - accuracy: 0.0827 - loss: 6.0490 - val_accuracy: 0.0938 - val_loss: 6.2857
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.1043 - loss: 5.7061 - val_accuracy: 0.1027 - val_loss: 6.2743
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 64ms/step - accuracy: 0.1202 - loss: 5.4241 - val_accuracy: 0.1075 - val_loss: 6.3060
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.1334 - loss: 5.1686 - val_accuracy: 0.1116 - val_loss: 6.3614
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.1447 - loss: 4.9334 - val_accuracy: 0.1111 - val_loss: 6.4081
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 64ms/step - accuracy: 0.1592 - loss: 4.7135 - val_accuracy: 0.1118 - val_loss: 6.4899
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 65ms/step - accuracy: 0.1760 - loss: 4.5080 - val_accuracy: 0.1115 - val_loss: 6.5390
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.1977 - loss: 4.3163 - val_accuracy: 0.1091 - val_loss: 6.6170
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.2187 - loss: 4.1336 - val_accuracy: 0.1088 - val_loss: 6.6827
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.2409 - loss: 3.9628 - val_accuracy: 0.1043 - val_loss: 6.7684
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.2636 - loss: 3.8056 - val_accuracy: 0.1079 - val_loss: 6.8639
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 64ms/step - accuracy: 0.2846 - loss: 3.6587 - val_accuracy: 0.1048 - val_loss: 6.9307
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.3044 - loss: 3.5236 - val_accuracy: 0.0994 - val_loss: 7.0170
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.3239 - loss: 3.4144 - val_accuracy: 0.0976 - val_loss: 7.1035
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.3434 - loss: 3.2876 - val_accuracy: 0.0992 - val_loss: 7.1748
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.3597 - loss: 3.1780 - val_accuracy: 0.0957 - val_loss: 7.2512
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.3710 - loss: 3.1136 - val_accuracy: 0.0938 - val_loss: 7.3220
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.3912 - loss: 2.9906 - val_accuracy: 0.0945 - val_loss: 7.3774
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.4068 - loss: 2.9031 - val_accuracy: 0.0937 - val_loss: 7.4609
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.4196 - loss: 2.8209 - val_accuracy: 0.0939 - val_loss: 7.5226
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 66ms/step - accuracy: 0.4311 - loss: 2.7459 - val_accuracy: 0.0929 - val_loss: 7.5906
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.4427 - loss: 2.6738 - val_accuracy: 0.0943 - val_loss: 7.6592
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 66ms/step - accuracy: 0.4562 - loss: 2.6052 - val_accuracy: 0.0907 - val_loss: 7.7228
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.4668 - loss: 2.5426 - val_accuracy: 0.0916 - val_loss: 7.7901
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.4776 - loss: 2.4818 - val_accuracy: 0.0885 - val_loss: 7.8550
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.4832 - loss: 2.4524 - val_accuracy: 0.0865 - val_loss: 7.9276
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.4918 - loss: 2.3940 - val_accuracy: 0.0864 - val_loss: 7.9668
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5059 - loss: 2.3228 - val_accuracy: 0.0888 - val_loss: 8.0269
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5160 - loss: 2.2714 - val_accuracy: 0.0849 - val_loss: 8.0865
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5229 - loss: 2.2266 - val_accuracy: 0.0821 - val_loss: 8.1550
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5317 - loss: 2.1857 - val_accuracy: 0.0846 - val_loss: 8.1994
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 64ms/step - accuracy: 0.5390 - loss: 2.1408 - val_accuracy: 0.0846 - val_loss: 8.2777
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5469 - loss: 2.1026 - val_accuracy: 0.0830 - val_loss: 8.3351
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5529 - loss: 2.0627 - val_accuracy: 0.0846 - val_loss: 8.3893
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5598 - loss: 2.0292 - val_accuracy: 0.0815 - val_loss: 8.4442
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5648 - loss: 1.9972 - val_accuracy: 0.0823 - val_loss: 8.4927
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5730 - loss: 1.9591 - val_accuracy: 0.0805 - val_loss: 8.5700
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5798 - loss: 1.9272 - val_accuracy: 0.0809 - val_loss: 8.6156
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5845 - loss: 1.9000 - val_accuracy: 0.0836 - val_loss: 8.6709
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5905 - loss: 1.8677 - val_accuracy: 0.0816 - val_loss: 8.7187
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5945 - loss: 1.8434 - val_accuracy: 0.0839 - val_loss: 8.7776
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6012 - loss: 1.8160 - val_accuracy: 0.0801 - val_loss: 8.8299
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6057 - loss: 1.7881 - val_accuracy: 0.0786 - val_loss: 8.8815
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6112 - loss: 1.7627 - val_accuracy: 0.0780 - val_loss: 8.9488
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6154 - loss: 1.7434 - val_accuracy: 0.0787 - val_loss: 8.9806
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5990 - loss: 1.8150 - val_accuracy: 0.0774 - val_loss: 9.0189
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6226 - loss: 1.7035 - val_accuracy: 0.0793 - val_loss: 9.0747
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 65ms/step - accuracy: 0.6298 - loss: 1.6730 - val_accuracy: 0.0800 - val_loss: 9.1209
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6337 - loss: 1.6515 - val_accuracy: 0.0741 - val_loss: 9.1591
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6151 - loss: 1.7318 - val_accuracy: 0.0762 - val_loss: 9.2354
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.5963 - loss: 1.8040 - val_accuracy: 0.0772 - val_loss: 9.2164
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6386 - loss: 1.6200 - val_accuracy: 0.0788 - val_loss: 9.2907
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6465 - loss: 1.5824 - val_accuracy: 0.0786 - val_loss: 9.3167
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6508 - loss: 1.5632 - val_accuracy: 0.0761 - val_loss: 9.3745
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6526 - loss: 1.5518 - val_accuracy: 0.0783 - val_loss: 9.4120
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6568 - loss: 1.5347 - val_accuracy: 0.0787 - val_loss: 9.4789
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6560 - loss: 1.5297 - val_accuracy: 0.0759 - val_loss: 9.5220
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 66ms/step - accuracy: 0.6597 - loss: 1.5145 - val_accuracy: 0.0754 - val_loss: 9.5888
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6614 - loss: 1.4980 - val_accuracy: 0.0753 - val_loss: 9.6032
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6649 - loss: 1.4837 - val_accuracy: 0.0727 - val_loss: 9.6530
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 65ms/step - accuracy: 0.6663 - loss: 1.4691 - val_accuracy: 0.0742 - val_loss: 9.6739
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6722 - loss: 1.4545 - val_accuracy: 0.0749 - val_loss: 9.7405
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6744 - loss: 1.4408 - val_accuracy: 0.0735 - val_loss: 9.7957
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6765 - loss: 1.4249 - val_accuracy: 0.0755 - val_loss: 9.8296
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 65ms/step - accuracy: 0.6785 - loss: 1.4162 - val_accuracy: 0.0746 - val_loss: 9.8534
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6805 - loss: 1.4079 - val_accuracy: 0.0722 - val_loss: 9.8943
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6835 - loss: 1.3932 - val_accuracy: 0.0736 - val_loss: 9.9580
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6864 - loss: 1.3778 - val_accuracy: 0.0719 - val_loss: 9.9774
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 65ms/step - accuracy: 0.6879 - loss: 1.3711 - val_accuracy: 0.0719 - val_loss: 10.0431
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 66ms/step - accuracy: 0.6891 - loss: 1.3606 - val_accuracy: 0.0759 - val_loss: 10.0723
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6909 - loss: 1.3531 - val_accuracy: 0.0717 - val_loss: 10.1066
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6942 - loss: 1.3384 - val_accuracy: 0.0736 - val_loss: 10.1535
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6941 - loss: 1.3377 - val_accuracy: 0.0710 - val_loss: 10.1930
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6985 - loss: 1.3196 - val_accuracy: 0.0702 - val_loss: 10.2343
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.6989 - loss: 1.3117 - val_accuracy: 0.0680 - val_loss: 10.2792
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7008 - loss: 1.3062 - val_accuracy: 0.0707 - val_loss: 10.2860
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7030 - loss: 1.2990 - val_accuracy: 0.0680 - val_loss: 10.3517
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 66ms/step - accuracy: 0.7046 - loss: 1.2875 - val_accuracy: 0.0707 - val_loss: 10.3794
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 66ms/step - accuracy: 0.7047 - loss: 1.2833 - val_accuracy: 0.0708 - val_loss: 10.4230
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7082 - loss: 1.2719 - val_accuracy: 0.0710 - val_loss: 10.4656
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7115 - loss: 1.2590 - val_accuracy: 0.0725 - val_loss: 10.4952
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7108 - loss: 1.2554 - val_accuracy: 0.0707 - val_loss: 10.5696
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7104 - loss: 1.2523 - val_accuracy: 0.0725 - val_loss: 10.5554
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7157 - loss: 1.2354 - val_accuracy: 0.0686 - val_loss: 10.5926
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7160 - loss: 1.2272 - val_accuracy: 0.0715 - val_loss: 10.6390
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7146 - loss: 1.2298 - val_accuracy: 0.0692 - val_loss: 10.6755
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7184 - loss: 1.2198 - val_accuracy: 0.0687 - val_loss: 10.7197
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7174 - loss: 1.2196 - val_accuracy: 0.0676 - val_loss: 10.7387
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7196 - loss: 1.2152 - val_accuracy: 0.0705 - val_loss: 10.7845
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7223 - loss: 1.2020 - val_accuracy: 0.0676 - val_loss: 10.8448
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 66ms/step - accuracy: 0.7226 - loss: 1.1930 - val_accuracy: 0.0692 - val_loss: 10.8429
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 66ms/step - accuracy: 0.7217 - loss: 1.1926 - val_accuracy: 0.0688 - val_loss: 10.8745
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7241 - loss: 1.1889 - val_accuracy: 0.0665 - val_loss: 10.8866
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7288 - loss: 1.1669 - val_accuracy: 0.0692 - val_loss: 10.9287
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7265 - loss: 1.1773 - val_accuracy: 0.0700 - val_loss: 10.9681
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7247 - loss: 1.1788 - val_accuracy: 0.0683 - val_loss: 10.9969
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7306 - loss: 1.1590 - val_accuracy: 0.0704 - val_loss: 11.0274
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7306 - loss: 1.1554 - val_accuracy: 0.0677 - val_loss: 11.0546
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.7272 - loss: 1.1630 - val_accuracy: 0.0700 - val_loss: 11.0842

In [38]:
epochs = 100
batch_size = 128

lstm_history = lstm_model.fit(
   X_padded, y_one_hot,
  epochs=epochs,
  batch_size=batch_size,
  validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 56ms/step - accuracy: 0.0386 - loss: 6.7422 - val_accuracy: 0.0453 - val_loss: 6.6629
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.0600 - loss: 6.2981 - val_accuracy: 0.0698 - val_loss: 6.4973
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.0833 - loss: 6.0180 - val_accuracy: 0.0864 - val_loss: 6.4255
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.0985 - loss: 5.8056 - val_accuracy: 0.0958 - val_loss: 6.3896
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1110 - loss: 5.6168 - val_accuracy: 0.1038 - val_loss: 6.3625
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1225 - loss: 5.4352 - val_accuracy: 0.1068 - val_loss: 6.3769
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1312 - loss: 5.2691 - val_accuracy: 0.1113 - val_loss: 6.3921
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1404 - loss: 5.1177 - val_accuracy: 0.1115 - val_loss: 6.4295
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.1476 - loss: 4.9749 - val_accuracy: 0.1126 - val_loss: 6.4786
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1545 - loss: 4.8359 - val_accuracy: 0.1129 - val_loss: 6.5317
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1629 - loss: 4.7027 - val_accuracy: 0.1143 - val_loss: 6.6108
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1715 - loss: 4.5713 - val_accuracy: 0.1157 - val_loss: 6.6550
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1816 - loss: 4.4422 - val_accuracy: 0.1143 - val_loss: 6.7111
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1934 - loss: 4.3164 - val_accuracy: 0.1136 - val_loss: 6.7777
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2060 - loss: 4.1924 - val_accuracy: 0.1138 - val_loss: 6.8577
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2203 - loss: 4.0719 - val_accuracy: 0.1132 - val_loss: 6.9338
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2347 - loss: 3.9568 - val_accuracy: 0.1115 - val_loss: 7.0173
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2497 - loss: 3.8458 - val_accuracy: 0.1134 - val_loss: 7.0861
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2649 - loss: 3.7430 - val_accuracy: 0.1141 - val_loss: 7.1684
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2789 - loss: 3.6443 - val_accuracy: 0.1115 - val_loss: 7.2430
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2929 - loss: 3.5521 - val_accuracy: 0.1097 - val_loss: 7.3093
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3074 - loss: 3.4675 - val_accuracy: 0.1084 - val_loss: 7.3904
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3202 - loss: 3.3856 - val_accuracy: 0.1085 - val_loss: 7.4590
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3329 - loss: 3.3089 - val_accuracy: 0.1102 - val_loss: 7.5457
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3446 - loss: 3.2353 - val_accuracy: 0.1057 - val_loss: 7.6241
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3549 - loss: 3.1668 - val_accuracy: 0.1055 - val_loss: 7.6930
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3662 - loss: 3.0993 - val_accuracy: 0.1068 - val_loss: 7.7703
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.3776 - loss: 3.0375 - val_accuracy: 0.1061 - val_loss: 7.8345
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3875 - loss: 2.9755 - val_accuracy: 0.1028 - val_loss: 7.8965
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3977 - loss: 2.9183 - val_accuracy: 0.1043 - val_loss: 7.9720
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4065 - loss: 2.8614 - val_accuracy: 0.0999 - val_loss: 8.0563
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4164 - loss: 2.8062 - val_accuracy: 0.1014 - val_loss: 8.1044
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4252 - loss: 2.7537 - val_accuracy: 0.1014 - val_loss: 8.1630
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4350 - loss: 2.7018 - val_accuracy: 0.1020 - val_loss: 8.2355
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4432 - loss: 2.6529 - val_accuracy: 0.0986 - val_loss: 8.3071
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4538 - loss: 2.6056 - val_accuracy: 0.0983 - val_loss: 8.3476
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.4600 - loss: 2.5596 - val_accuracy: 0.0999 - val_loss: 8.4165
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4697 - loss: 2.5155 - val_accuracy: 0.0984 - val_loss: 8.4884
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4780 - loss: 2.4707 - val_accuracy: 0.0937 - val_loss: 8.5404
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4855 - loss: 2.4279 - val_accuracy: 0.0965 - val_loss: 8.6088
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4929 - loss: 2.3872 - val_accuracy: 0.0960 - val_loss: 8.6719
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5013 - loss: 2.3457 - val_accuracy: 0.0949 - val_loss: 8.7271
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.5083 - loss: 2.3059 - val_accuracy: 0.0969 - val_loss: 8.7850
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5162 - loss: 2.2679 - val_accuracy: 0.0944 - val_loss: 8.8615
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.5229 - loss: 2.2311 - val_accuracy: 0.0932 - val_loss: 8.8969
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5289 - loss: 2.1964 - val_accuracy: 0.0939 - val_loss: 8.9727
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5363 - loss: 2.1605 - val_accuracy: 0.0938 - val_loss: 9.0374
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5438 - loss: 2.1260 - val_accuracy: 0.0911 - val_loss: 9.0950
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5498 - loss: 2.0921 - val_accuracy: 0.0941 - val_loss: 9.1565
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.5564 - loss: 2.0606 - val_accuracy: 0.0916 - val_loss: 9.1973
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5633 - loss: 2.0267 - val_accuracy: 0.0935 - val_loss: 9.2613
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5697 - loss: 1.9941 - val_accuracy: 0.0903 - val_loss: 9.3277
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5748 - loss: 1.9653 - val_accuracy: 0.0904 - val_loss: 9.3844
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5807 - loss: 1.9344 - val_accuracy: 0.0926 - val_loss: 9.4350
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.5870 - loss: 1.9064 - val_accuracy: 0.0894 - val_loss: 9.5090
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5922 - loss: 1.8782 - val_accuracy: 0.0888 - val_loss: 9.5516
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5977 - loss: 1.8506 - val_accuracy: 0.0861 - val_loss: 9.6138
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6036 - loss: 1.8221 - val_accuracy: 0.0877 - val_loss: 9.6576
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6100 - loss: 1.7950 - val_accuracy: 0.0883 - val_loss: 9.7189
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6150 - loss: 1.7707 - val_accuracy: 0.0863 - val_loss: 9.7745
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6188 - loss: 1.7453 - val_accuracy: 0.0867 - val_loss: 9.8341
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6260 - loss: 1.7185 - val_accuracy: 0.0836 - val_loss: 9.8830
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6302 - loss: 1.6957 - val_accuracy: 0.0868 - val_loss: 9.9305
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6343 - loss: 1.6710 - val_accuracy: 0.0853 - val_loss: 9.9726
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6393 - loss: 1.6477 - val_accuracy: 0.0874 - val_loss: 10.0405
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6449 - loss: 1.6256 - val_accuracy: 0.0829 - val_loss: 10.0966
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6492 - loss: 1.6042 - val_accuracy: 0.0857 - val_loss: 10.1520
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6542 - loss: 1.5800 - val_accuracy: 0.0810 - val_loss: 10.2182
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6592 - loss: 1.5603 - val_accuracy: 0.0819 - val_loss: 10.2679
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6640 - loss: 1.5366 - val_accuracy: 0.0856 - val_loss: 10.3258
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6668 - loss: 1.5188 - val_accuracy: 0.0841 - val_loss: 10.3481
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 55ms/step - accuracy: 0.6719 - loss: 1.4979 - val_accuracy: 0.0856 - val_loss: 10.4223
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6747 - loss: 1.4786 - val_accuracy: 0.0829 - val_loss: 10.4768
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6801 - loss: 1.4573 - val_accuracy: 0.0810 - val_loss: 10.5223
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6855 - loss: 1.4393 - val_accuracy: 0.0820 - val_loss: 10.5552
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6879 - loss: 1.4214 - val_accuracy: 0.0817 - val_loss: 10.6122
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6914 - loss: 1.4038 - val_accuracy: 0.0788 - val_loss: 10.6872
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6961 - loss: 1.3854 - val_accuracy: 0.0817 - val_loss: 10.7429
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7018 - loss: 1.3677 - val_accuracy: 0.0822 - val_loss: 10.7659
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7036 - loss: 1.3499 - val_accuracy: 0.0820 - val_loss: 10.8446
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7063 - loss: 1.3347 - val_accuracy: 0.0801 - val_loss: 10.8908
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7119 - loss: 1.3165 - val_accuracy: 0.0783 - val_loss: 10.9365
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7143 - loss: 1.3008 - val_accuracy: 0.0796 - val_loss: 10.9699
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7174 - loss: 1.2874 - val_accuracy: 0.0806 - val_loss: 11.0293
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7213 - loss: 1.2704 - val_accuracy: 0.0786 - val_loss: 11.0824
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7244 - loss: 1.2541 - val_accuracy: 0.0779 - val_loss: 11.1113
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7273 - loss: 1.2407 - val_accuracy: 0.0775 - val_loss: 11.1698
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7304 - loss: 1.2244 - val_accuracy: 0.0790 - val_loss: 11.2321
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7340 - loss: 1.2119 - val_accuracy: 0.0799 - val_loss: 11.2803
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7368 - loss: 1.1976 - val_accuracy: 0.0775 - val_loss: 11.3397
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7397 - loss: 1.1836 - val_accuracy: 0.0780 - val_loss: 11.3919
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7429 - loss: 1.1687 - val_accuracy: 0.0790 - val_loss: 11.4089
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7470 - loss: 1.1547 - val_accuracy: 0.0749 - val_loss: 11.4561
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.7487 - loss: 1.1438 - val_accuracy: 0.0776 - val_loss: 11.5382
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7520 - loss: 1.1297 - val_accuracy: 0.0778 - val_loss: 11.5760
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 55ms/step - accuracy: 0.7533 - loss: 1.1174 - val_accuracy: 0.0778 - val_loss: 11.6271
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7567 - loss: 1.1049 - val_accuracy: 0.0779 - val_loss: 11.6543
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.7579 - loss: 1.0935 - val_accuracy: 0.0775 - val_loss: 11.7007
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7622 - loss: 1.0783 - val_accuracy: 0.0758 - val_loss: 11.7645
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7634 - loss: 1.0710 - val_accuracy: 0.0793 - val_loss: 11.7854

In [69]:
from tensorflow.keras.models import load_model

In [80]:
lstm_model = load_model("lstm_model.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [81]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [72]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word[index] = word

In [73]:

from tensorflow.keras.preprocessing.sequence import pad_sequences

In [74]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [75]:
seed_text = "what are you"
next_word = predictor(lstm_model,tokenizer,seed_text,max_len)
print(next_word)

implying

In [76]:
def generate_text(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [77]:
seed = "are you a "
generate_text = generate_text(lstm_model,tokenizer,seed,max_len,10)
print(generate_text)

are you a  very naughty you care about you you are the best

In [78]:
import pickle
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokenizer, f)

In [79]:
with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)